### ISSUE TITLE
safe/exec.go 中的写法实际存在安全风险

### ISSUE THREAD

**Issue by Li4n0** [leveryd/go-sec-code#2]
问题出现在 go-sec-code/pkg/handler/safe/exec.go 这个例子

```go
func DigHost(c *gin.Context) {
	host, exists := c.GetQuery("host")
	if exists == false {
		c.JSON(200, "no host arg")
		return
	}

	// safe
	command := "dig " + host
	commandResults, err := exec.Command(strings.Split(command, " ")[0], strings.Split(command, " ")[1:]...).Output()
	//commandResults, err := exec.Command(command).Output()	//
	if err != nil {
		c.JSON(200, "fail to execute")
		return
	}
	c.Writer.Write(commandResults)
}
```

这段代码被错误地认为是`safe`的，实际上这种写法允许攻击者传入任何参数，存在严重的参数注入风险。
同样以代码中使用的 `dig` 命令为例，`dig`存在`-f`参数，用来在文件中读取要查找的`host`列表，如攻击者传入的`host`值为 `-f /etc/uuid`，将会把文件中的内容回显在命令执行结果中，实现文件读取：

<img width="614" alt="image" src="https://user-images.githubusercontent.com/34324462/163665967-be91a19e-1188-4a0b-91b9-b0bc47dcd0f4.png">

在该例子的写法的基础上，如果将完整的`stderr`返回，或者是使用其他命令，将可能造成更严重的问题。

**Comment by leveryd** [comment]
感谢师傅的关注和指正，已经修改，师傅有空可以看下。

**Comment by Li4n0** [comment]
> 感谢师傅的关注和指正，已经修改，师傅有空可以看下。

 这样修改后是安全的，但是`host`过了一层白名单后，这部分操作其实就没必要了：

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/34324462/163698934-04084e00-c49b-4724-9bce-bf3a302b419d.png">

**Comment by leveryd** [comment]
已修改
